//input field which has default value should have class .need-clean
//input field which has info msg should have class .has-info
//info msg is <span>, has class .info-msg 
//error msg generated by validator plug-in is <label>, has class .error
//input field which only contain 0-9 has class .number-only
//if the info msg need to be put in next line, add a <br/> before all info messages.

function scrollTo(id, time) {
	$('html, body').animate({
		scrollTop: $(id).offset().top
	}, time);
}

function processCreateGroupForm() {
	$('input[type="radio"]').prop('checked', false); //important - need this one, otherwise ctrl R will not refresh radio button and other field, casing the form go into a bug state.
	$('#group-1st-row').nextAll('div').hide();//hide all after 1st Q
	$('#group-1st-row').hide().delay(100).fadeIn();

	//------------------------------- class group's questions ------------------------------------

	$('input[name=class-group]').change(function() {
		if ($('#not-class-group').is(":checked")) { 		// not a class group
			$('#group-1st-row').nextAll('div').hide();		// hide all after 1st Q
			$('#group-5th-row').fadeIn();					// ask if it is a school group
			$('#is-school-group').prop('checked', false);	// unselect is-school-group radio button first
			$('#not-school-group').prop('checked', false);	// unselect not-school-group radio button first
		} else {											// it is a class group
			$('#group-2nd-row').fadeIn();					// show 1st class group's question
			$('#group-2nd-row').nextAll('div').hide();		// hide all rest questions
			$('#class-group-label').nextAll('select').val(0);// set all select field to 0 first
			$('#school-country-0').nextAll('select').attr('disabled', true); //enable school contry only
			$('#is-school-group').prop('checked', false);	// unselect is-school-group radio button first 
			$('#not-school-group').prop('checked', false);	// unselect not-school-group radio button first
		}
	}); //end change

	$('#school-country-0').change(function() {
		$(this).nextAll('select').val(0);
		$(this).next('select').nextAll('select').attr('disabled', true);
		$('#group-2nd-row').nextAll('div').hide();

		if($(this).val() == 0) {
			$(this).nextAll('select').attr('disabled', true);
		} else {
			$(this).next('select').attr('disabled', false);			
		}
	}); //end change

	$('#school-region-0').change(function() {
		$(this).nextAll('select').val(0);
		$(this).next('select').nextAll('select').attr('disabled', true);
		$('#group-2nd-row').nextAll('div').hide();

		if($(this).val() == 0) {
			$(this).nextAll('select').attr('disabled', true);
		} else {
			$(this).next('select').attr('disabled', false);			
		}
	}); //end change

	$('#school-type-0').change(function() {
		$(this).nextAll('select').val(0);
		$('#group-2nd-row').nextAll('div').hide();

		if($(this).val() == 0) {
			$(this).nextAll('select').attr('disabled', true);
		} else {
			$(this).next('select').attr('disabled', false);				
		}
	}); //end change

	$('#school-name-0').change(function() {
		$('#group-2nd-row').nextAll('div').hide();

		if($(this).val() == 0) {
			$('#group-2nd-row').nextAll('div').hide();
		} else {
			$('#group-2nd-row').next('div').fadeIn();
			type = $('#school-type-0').val();
			if (type == 1) { 						
				//graduate school and Phd - only has department
				
				$('#group-3rd-row').html('')
				.append('<label for="grad-department" class="describe-label">科系:</label>') 
				.append('<select name="grad-department" id="grad-department"> <option value="0">--系所--</option><option value="1">外文系</option><option value="2">中文系</option><option value="3">經濟系</option><option value="4">企管系</option><option value="5">資工系</option><option value="6">化工系</option><option value="7">醫學系</option><option value="8">牙醫系</option><option value="9">土木系</option></select>');

				$('#grad-department').val(0);

				$('#grad-department').change(function() {
					if($(this).val() == 0) {
						$('#group-7th-row').nextAll('div').hide();
					} else {
						$('#group-9th-row').fadeIn();
						$('#group-12th-row').fadeIn();
					}	
				}); //end change

			} else if (type == 2 || type == 3 || type == 4 || type == 5 || type == 6) { 	
				//has a department and a year
				
				$('#group-3rd-row').html('').append('<div id="under-depart-div" class="same-line"></div>');		
				$('#under-depart-div').append('<label for="under-department" class="describe-label">科系:</label>')
				.append('<select name="under-department" id="under-department"> <option value="0">--系所--</option><option value="1">外文系</option><option value="2">中文系</option><option value="3">經濟系</option></select>');
			
				$('#under-depart-div').after('<div id="under-year-div" class="same-line"></div>');
				$('#under-year-div').append('<label for="under-year" class="describe-label">年級:</label>')
				.append('<select name="under-year" id="under-year"> <option value="0">--年級--</option><option value="1">一年級</option><option value="2">二年級</option><option value="3">三年級</option><option value="4">四年級</option></select>');
				
				$('#under-year-div').hide();
				$('#under-department').val(0);

				$('#under-department').change(function() {
					if($(this).val() == 0) {
						$('#under-year-div').hide();
						$('#under-year').val(0);
						$('#group-3rd-row').nextAll('div').hide();
					} else {
						$('#under-year-div').fadeIn();		
					}	
				}); //end change
				
				$('#under-year').change(function() {
					if($(this).val() == 0) {
						$('#group-3rd-row').nextAll('div').hide();
					} else {
						$('#group-4th-row').fadeIn();
						$('#graduate-year').val(0);
					}				
				}); //end change
			
			} else if (type == 7 || type == 8 || type == 9) {					
				//has a year and a class
				
				$('#group-3rd-row').html('').append('<div id="year-n-class-year-div" class="same-line"></div>');
				$('#year-n-class-year-div').append('<label for="year-n-class-year" class="describe-label">年級:</label>') 	
				.append('<select name="year-n-class-year" id="year-n-class-year"> <option value="0">--年級--</option><option value="1">一年級</option><option value="2">二年級</option><option value="3">三年級</option></select>');
				
				$('#year-n-class-year-div').after('<div id="year-n-class-class-div" class="same-line"></div>');
				$('#year-n-class-class-div').append('<label for="year-n-class-class" class="describe-label">班級:</label>')
				.append('<input name="year-n-class-class" type="text" id="year-n-class-class" size="2" maxlength="2"><span class="text-field-word"> 班 </span> <span class="text-field-explan"> (請輸入正確的班級名稱, ex. 3, 12, 孝, 仁) </span>');
				
				$('#year-n-class-year').val(0);
				$('#year-n-class-class-div').hide();
				
				$('#year-n-class-year').change(function() {
					if($(this).val() == 0) {
						$('#year-n-class-class-div').hide().val(0);
						$('#group-3rd-row').nextAll('div').hide();
					} else {
						$('#year-n-class-class-div').fadeIn();
						$('#group-4th-row').fadeIn();
						$('#graduate-year').val(0);
						$('#year-n-class-class').focus();		
					}				
				}); //end change
			} //school type condition
		} //type is not 0 
	}); //end change
	
	$('#graduate-year').change(function() {
		if($(this).val() == 0) {
			$('#group-4th-row').nextAll('div').hide();
		} else {
			$('#group-9th-row').fadeIn();
			$('#group-12th-row').fadeIn();
			//scrollTo("#submit-create-group", 0);
		}	
	}); //end change;
	
	//------------------------------- school group's questions ------------------------------------

	$('input[name=school-group]').change(function() {		
		if ($('#not-school-group').is(":checked")) { //not a class group
			$('#group-5th-row').nextAll('div').hide();//hide all after 1st Q
			$('#group-7th-row').nextAll('div').fadeIn();
			$('#group-name').focus();	
			$('#group-region').attr('disabled', true);	
		} else {
			$('#group-6th-row').fadeIn();
			$('#group-6th-row').nextAll('div').hide();
			$('#school-group-label').nextAll('select').val(0);
			$('#school-country-1').nextAll('select').attr('disabled', true);
		}
	}); //end change

	$('#school-country-1').change(function() {
		$(this).nextAll('select').val(0);
		$(this).next('select').nextAll('select').attr('disabled', true);
		$('#group-6th-row').nextAll('div').hide();

		if($(this).val() == 0) {
			$(this).nextAll('select').attr('disabled', true);
		} else {
			$(this).next('select').attr('disabled', false);			
		}
	}); //end change

	$('#school-region-1').change(function() {
		$(this).nextAll('select').val(0);
		$(this).next('select').nextAll('select').attr('disabled', true);
		$('#group-6th-row').nextAll('div').hide();

		if($(this).val() == 0) {
			$(this).nextAll('select').attr('disabled', true);
		} else {
			$(this).next('select').attr('disabled', false);			
		}
	}); //end change

	$('#school-type-1').change(function() {
		$(this).nextAll('select').val(0);
		$('#group-6th-row').nextAll('div').hide();

		if($(this).val() == 0) {
			$(this).nextAll('select').attr('disabled', true);
		} else {
			$(this).next('select').attr('disabled', false);	
		}
	}); //end change

	$('#school-name-1').change(function() {
		if($(this).val() == 0) {
			$('#group-6th-row').nextAll('div').hide();
		} else {
			$('#group-7th-row').fadeIn();
			$('#group-9th-row').fadeIn();
			$('#group-11th-row').fadeIn();
			$('#group-12th-row').fadeIn();		
			$('#school-group-name').focus();
		}
	}); //end change

	$('#school-group-name').focus(function() {
		if (this.value === this.defaultValue) {
			this.value = '';
		}
	}).blur(function() {
		if (this.value === '') {
			this.value = this.defaultValue;
		}
	});

	//------------------------------- general questions ------------------------------------

	$('#group-name').focus(function() {
		if (this.value === this.defaultValue) {
			this.value = '';
		}
	}).blur(function() {
		if (this.value === '') {
			this.value = this.defaultValue;
		}
	});

	$('#group-describe').focus(function() {
		if (this.value === this.defaultValue) {
			this.value = '';
		}
	}).blur(function() {
		if (this.value === '') {
			this.value = this.defaultValue;
		}
	});

	$('#group-country').change(function() {
		$(this).next('select').val(0);

		if($(this).val() == 0) {
			$(this).next('select').attr('disabled', true);
		} else {
			$(this).next('select').attr('disabled', false);			
		}
	}); //end change

	$('#none-area').change(function() {
		if ($(this).is(":checked")) { 
			$('#group-country').val(0).attr('disabled', true).hide();
			$('#group-region').val(0).attr('disabled', true).hide();
			$('#group-10th-row').next('label.error').hide();
		} else {
			$('#group-country').attr('disabled', false).fadeIn();
			$('#group-region').fadeIn();
		}
	}); //end change
	
	//--------------------validation-----------------------

	jQuery.validator.addMethod("validGroupDescribe", function(value, element, param) {
		//value = "ex. 張君雅"
		//element is name element
		//param is passed in by the rules
		return (value != element.defaultValue) && (value != "");
	}, "請簡短介紹, 讓其他使用者能更了解這個群組");

	jQuery.validator.addMethod("validGroupName", function(value, element, param) {
		return (value != element.defaultValue && value != "") || ($('#group-name').is(":hidden"));
	}, "請替您的群組取一個名字");

	jQuery.validator.addMethod("validGroupArea", function(value, element, param) {
		return (value != 0) || ($('#none-area').is(":checked")) || $('#none-area').is(":hidden");
	}, '請選擇群組地區. 如果不限地區, 請勾選「不限於特定地區」');

	jQuery.validator.addMethod("validSchoolGroupName", function(value, element, param) {
		return (value != element.defaultValue) || ($('#school-group-name').is(":hidden"));
	}, "請輸入社團名稱");

	jQuery.validator.addMethod("validGraduateYear", function(value, element, param) {
		return (value != 0) || ($('#graduate-year').is(":hidden"));
	}, "請選擇畢業年份");

	$('#create-group-form').validate({
		rules: {
			"school-group-name": {
				validSchoolGroupName: true
			},
			"group-describe": {
				validGroupDescribe: true
			},
			"group-name": {
				validGroupName: true
			},
			"group-country": {
				validGroupArea: true
			},
			"group-region": {
				validGroupArea: true
			},
			"graduate-year": {
				validGraduateYear: true
			}
		},
		errorPlacement: function(error, element) {
			if (element.is("#group-country, #group-region")) {
				error.insertAfter("#group-10th-row");
			} else {
				error.insertAfter(element);
			}
		}
	}); //end validate
}

function processLogInForm(){
	//register submit function to disable submit button when submitted
	//conflict with varification
	// disableWhenSubmit($('#logIn-form'));
	
	$('#logIn-form').validate({
		rules: {
			account: {
				required: true
			},
			password: {
				required: true
			}
		},
		messages: {
			account: {
				required: "請輸入您的帳號"
			},
			password: {
				required: "請輸入您的密碼"
			}
		}
	}); // end validate
	$('input').eq(0).focus();
}

function processRegisterForm(){
	//register submit function to disable submit button when submitted
	//conflict with varification
	// disableWhenSubmit($('#register-form'));

 	//allow number only in .number-only input field.
	$('.number-only').keyup(function() {
		value = $(this).val();
		$(this).val(value.replace(/[^0-9\.]/g,''));
	}); //end keyup

	//auto focus on #day when user input 2 digits and it is valid month
	$('#month').keyup(function() {
		value = $(this).val();
		if (value.length == 2) {
			if (value <= 12 && value >= 1) {
				$(this).siblings('#day').focus();
			}
		}
	}); //end keyup
	
	//auto focus on #year when user input 2 digits and it is valid day
	$('#day').keyup(function() {
		day = $(this).val();
		month = $('#month').val();
		if (day.length == 2) {
			if (((month==1 || month==3 || month==5 || month==7 || month==8 || month==10 || month==12) && (day>=1) && (day<=31))
				|| ((month==4 || month==6 || month==9 || month==11) && (day >= 1) && (day <= 30))
				|| (month==2 && day >= 1 && day <= 29)) {
				$(this).siblings('#year').focus();
			}
		}
	}); //end keyup

	//auto blur when user type in 4 digits in year field
	$('#year').keyup(function() {
		if ($(this).val().length == 4) {
			$(this).blur();
		}
	}); //end keyup

 	//change #day and #month from 2 to 02 when blured.
	$('#day, #month').blur(function() {
		value = $(this).val();
		if (value > 0 && value.length < 2) {
			$(this).val("0" + value);
			$(this).next().focus();
		}
	}); //end blur
	
	$('.need-clean').focus(function() {
		var field = $(this);
		if (field.val()==field.prop('defaultValue')) {
			field.val('');
		}
	}); //end focus
	
	$('.need-clean').blur(function() {
		var field = $(this);
		if (field.val()=='') {
			field.val(field.prop('defaultValue'));
		}
	}); //end blur
	
	$('.has-info').focus(function() {
		if ($(this).siblings('label.error').length == 0 || //no error label
			$(this).siblings('label.error').is(":hidden")) //all error label is hidden
		{
			$(this).siblings('span').fadeIn(); //show info msg
		}
	}); //end focus
	
	$('.has-info').blur(function() {
		$(this).siblings('span').hide(); //hide info msg
	}); //end blur
	
	jQuery.validator.addMethod("notEqual", function(value, element, param) {
		return this.optional(element) || (value != param);
	}, "怪怪的");

	jQuery.validator.addMethod("notDefault", function(value, element, param) {
		//value = "ex. 張君雅"
		//element is name element
		//param is passed in by the rules
		return value != element.defaultValue;
	}, "輸入不可和default值相同");

	jQuery.validator.addMethod("validDate", function(value, element) {
		day = value;
		month = $('#month').val();
		if (((month==1 || month==3 || month==5 || month==7 || month==8 || month==10 || month==12) && (day>=1) && (day<=31))
			|| ((month==4 || month==6 || month==9 || month==11) && (day >= 1) && (day <= 30))
			|| (month==2 && day >= 1 && day <= 29)) {
			return true;
		} else {
			return false;
		}
	}, "日期無效");

	$('#register-form').validate({
		groups: {
			dateOfBirth: "month day year"
		},
		rules: {
			name: {
				required: true,
				notDefault: true
			},
			//account: {
			//	required: true,
			//	remote: 'check_account.php'
			//},
			password: {
				required: true,
				rangelength: [3,16]
			},
			passwordconfirm: {
				required: true,
				equalTo:'#password'
			},
			email: {
				required: true,
				email: true
			},
			gender: {
				required: true
			},
			month: {
				required: true,
				notDefault: true,
				range: [1,12]
			},
			day: {
				required: true,
				notDefault: true,
				validDate: true
			},
			year: {
				required: true,
				notDefault: true,
				range: [1900,2050]
			},
			termOfUse: {
				required: true
			},
			region: {
				notEqual: 0
			}
		}, //end rules
		messages: {
			name: {
				required: "請輸入您的姓名",
				notDefault: "請輸入您的姓名"
			},
			account: {
				required: "請選擇您的MyClass帳號",
				remote: "此帳號已被人使用"
			},
			password: {
				required: "請設定密碼",
				rangelength: "密碼需介於3到16個字元"
			},
			passwordconfirm: {
				required: "請確認密碼",
				equalTo: "密碼和第一次輸入不一致"
			},
			email: {
				required: "請提供您的email, 以便系統計確認信給您",
				email: "請輸入正確的email信箱"
			},
			gender: {
				required: "請選擇您的性別"
			},
			month: {
				required: "請輸入您的生日",
				notDefault: "請輸入您的生日",
				range: "請輸入合理的日期"
			},
			day: {
				required: "請輸入您的生日",
				notDefault: "請輸入您的生日",
				validDate: "請輸入合理的日期"
			},
			year: {
				required: "請輸入您的生日",
				notDefault: "請輸入您的生日",
				range: "請輸入合理的日期"
			},
			termOfUse: {
				required: "請閱讀MyClass使用服務條款並勾選此欄位"
			},
			region: {
				notEqual: "請選擇您的所在地區"
			}
		},
		errorPlacement: function(error, element) {
			if (element.is(":radio") || element.is(":checkbox")) {
				error.appendTo(element.parent());
			} else if (element.is("#day") || element.is("#month") || element.is("#year")) {
				error.insertAfter(element.siblings('span')); //show error after info msg.
			} else {
				error.insertAfter(element);
			}
		}
	}); //end validate

	$('input').eq(0).focus();
}

function disableWhenSubmit(formElement)
{
	formElement.submit(function() {
		var subButton = $(this).find(':submit');
		subButton.attr('disabled', true);
		subButton.val('...傳送資料中');
	}); // end submit
}


